# Generated by Django 3.0.4 on 2020-03-26 02:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200326_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 26, 2, 8, 15, 76614, tzinfo=utc)),
        ),
    ]
